import { loadMemoryRows, pruneNoiseRecords, type SourceId } from "./inspect-memories-data.js";

export type InspectMemoryOptions = {
  source: SourceId;
  scope?: "user" | "workspace" | "session";
  limit: number;
  contradictionsOnly: boolean;
  json: boolean;
  pruneNoise?: boolean;
};

export async function runInspectMemories(workspaceDir: string, options: InspectMemoryOptions): Promise<void> {
  if (options.pruneNoise) {
    const removed = await pruneNoiseRecords(workspaceDir, options.source);
    console.log(`Pruned autogenerated noise memories: ${removed}`);
  }

  const rows = await loadMemoryRows(workspaceDir, options.source);
  const byId = new Map(rows.map((row) => [row.id, row]));
  const filtered = rows
    .filter((row) => (options.scope ? row.scope === options.scope : true))
    .filter((row) => (options.contradictionsOnly ? Boolean(row.contradictoryTo) : true))
    .sort((a, b) => (a.provenance?.capturedAt ?? "").localeCompare(b.provenance?.capturedAt ?? "") * -1)
    .slice(0, options.limit);

  if (options.json) {
    console.log(JSON.stringify(filtered, null, 2));
    return;
  }

  console.log(`Inspect: memories (${filtered.length}/${rows.length} shown)`);
  if (!filtered.length) {
    console.log("- no matching memory records");
    if (!options.pruneNoise) process.exitCode = 1;
    return;
  }

  for (const row of filtered) {
    console.log(`- [${row.from}] ${row.id} scope=${row.scope} confidence=${row.confidence}`);
    console.log(`  statement: ${row.statement}`);
    if (row.context?.category) console.log(`  category: ${row.context.category}`);
    if (row.context?.tags?.length) console.log(`  tags: ${row.context.tags.join(", ")}`);
    if (row.capture?.horizon) console.log(`  horizon: ${row.capture.horizon}`);
    if (row.capture?.expiresAt) console.log(`  expiresAt: ${row.capture.expiresAt}`);
    if (row.capture?.reason) console.log(`  reason: ${row.capture.reason}`);
    if (row.capture?.references?.length) {
      const refs = row.capture.references.map((ref) => `${ref.kind}:${ref.value}`).join("; ");
      console.log(`  references: ${refs}`);
    }
    console.log(`  captured: ${row.provenance?.capturedAt ?? "unknown"} source=${row.provenance?.source ?? "unknown"}`);
    if (row.contradictoryTo) {
      const target = byId.get(row.contradictoryTo);
      console.log(`  contradictoryTo: ${row.contradictoryTo}${target ? ` -> ${target.statement}` : ""}`);
    }
  }
}