import type { Command } from "commander";
import { cwd } from "node:process";
import { runInspectInsights } from "./inspect-insights.js";
import { runInspectMemories } from "./inspect-memories.js";

export function registerInspectCommand(program: Command): void {
  const inspectCommand = program.command("inspect").description("Inspect memories and generated insights");

  inspectCommand.command("memories").description("Inspect memory records from local backends")
    .option("--source <source>", "file|copilot|honcho|all", "all")
    .option("--scope <scope>", "user|workspace|session")
    .option("--limit <number>", "maximum rows", "20")
    .option("--prune-noise", "remove autogenerated Observed* noise before listing", false)
    .option("--json", "print raw JSON", false)
    .action(async (options: { source: "file" | "copilot" | "honcho" | "all"; scope?: "user" | "workspace" | "session"; limit: string; pruneNoise: boolean; json: boolean }) => {
      await runInspectMemories(cwd(), {
        source: options.source,
        scope: options.scope,
        limit: Number(options.limit),
        contradictionsOnly: false,
        pruneNoise: options.pruneNoise,
        json: options.json
      });
    });

  inspectCommand.command("contradictions").description("Inspect only contradictory memory records")
    .option("--source <source>", "file|copilot|honcho|all", "all")
    .option("--limit <number>", "maximum rows", "20")
    .option("--prune-noise", "remove autogenerated Observed* noise before listing", false)
    .option("--json", "print raw JSON", false)
    .action(async (options: { source: "file" | "copilot" | "honcho" | "all"; limit: string; pruneNoise: boolean; json: boolean }) => {
      await runInspectMemories(cwd(), {
        source: options.source,
        limit: Number(options.limit),
        contradictionsOnly: true,
        pruneNoise: options.pruneNoise,
        json: options.json
      });
    });

  inspectCommand.command("insights").description("Inspect latest evaluation and pipeline insights")
    .option("--json", "print raw JSON", false)
    .action(async (options: { json: boolean }) => runInspectInsights(cwd(), options.json));
}