import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { MemoryRecord } from "../core/types.js";

type SourceId = "file" | "copilot" | "honcho" | "all";

export type InspectMemoryOptions = {
  source: SourceId;
  scope?: "user" | "workspace" | "session";
  limit: number;
  contradictionsOnly: boolean;
  json: boolean;
  pruneNoise?: boolean;
};

const MEMORY_PATHS = {
  file: ".dreamer/memory.json",
  copilot: ".dreamer/copilot-memory.json",
  honcho: ".dreamer/honcho/workspace.json"
} as const;

function selectedSources(source: SourceId): Array<Exclude<SourceId, "all">> {
  return source === "all" ? ["file", "copilot", "honcho"] : [source];
}

function isNoiseMemory(record: MemoryRecord): boolean {
  return record.statement.startsWith("Observed ");
}

function filterNoise(records: MemoryRecord[]): MemoryRecord[] {
  return records.filter((record) => !isNoiseMemory(record));
}

async function pruneNoiseAtPath(path: string): Promise<number> {
  try {
    const raw = await readFile(path, "utf8");
    const parsed = JSON.parse(raw) as unknown;

    if (Array.isArray(parsed)) {
      const next = filterNoise(parsed as MemoryRecord[]);
      const removed = parsed.length - next.length;
      if (removed > 0) await writeFile(path, JSON.stringify(next, null, 2), "utf8");
      return removed;
    }

    if (!parsed || typeof parsed !== "object") return 0;
    const record = parsed as Record<string, unknown>;
    let removed = 0;

    if (Array.isArray(record.records)) {
      const current = record.records as MemoryRecord[];
      const next = filterNoise(current);
      removed += current.length - next.length;
      record.records = next;
      if (record.counts && typeof record.counts === "object") {
        record.counts = {
          user: next.filter((entry) => entry.scope === "user").length,
          workspace: next.filter((entry) => entry.scope === "workspace").length,
          session: next.filter((entry) => entry.scope === "session").length
        };
      }
    }

    if (Array.isArray(record.memory)) {
      const current = record.memory as MemoryRecord[];
      const next = filterNoise(current);
      removed += current.length - next.length;
      record.memory = next;
    }

    if (removed > 0) {
      await writeFile(path, JSON.stringify(record, null, 2), "utf8");
    }
    return removed;
  } catch {
    return 0;
  }
}

async function readRecords(path: string): Promise<MemoryRecord[]> {
  try {
    const parsed = JSON.parse(await readFile(path, "utf8")) as unknown;
    if (Array.isArray(parsed)) return parsed as MemoryRecord[];
    if (parsed && typeof parsed === "object") {
      const record = parsed as Record<string, unknown>;
      if (Array.isArray(record.records)) return record.records as MemoryRecord[];
      if (Array.isArray(record.memory)) return record.memory as MemoryRecord[];
    }
    return [];
  } catch {
    return [];
  }
}

async function loadBySource(workspaceDir: string, source: SourceId): Promise<Array<MemoryRecord & { from: string }>> {
  const selected = selectedSources(source);
  const out: Array<MemoryRecord & { from: string }> = [];
  for (const key of selected) {
    const rows = await readRecords(join(workspaceDir, MEMORY_PATHS[key]));
    for (const row of rows) out.push({ ...row, from: key });
  }
  return out;
}

export async function runInspectMemories(workspaceDir: string, options: InspectMemoryOptions): Promise<void> {
  if (options.pruneNoise) {
    let removed = 0;
    for (const key of selectedSources(options.source)) {
      removed += await pruneNoiseAtPath(join(workspaceDir, MEMORY_PATHS[key]));
    }
    console.log(`Pruned autogenerated noise memories: ${removed}`);
  }

  const rows = await loadBySource(workspaceDir, options.source);
  const byId = new Map(rows.map((row) => [row.id, row]));
  const filtered = rows
    .filter((row) => (options.scope ? row.scope === options.scope : true))
    .filter((row) => (options.contradictionsOnly ? Boolean(row.contradictoryTo) : true))
    .sort((a, b) => (a.provenance?.capturedAt ?? "").localeCompare(b.provenance?.capturedAt ?? "") * -1)
    .slice(0, options.limit);

  if (options.json) {
    console.log(JSON.stringify(filtered, null, 2));
    return;
  }

  console.log(`Inspect: memories (${filtered.length}/${rows.length} shown)`);
  if (!filtered.length) {
    console.log("- no matching memory records");
    if (!options.pruneNoise) process.exitCode = 1;
    return;
  }

  for (const row of filtered) {
    console.log(`- [${row.from}] ${row.id} scope=${row.scope} confidence=${row.confidence}`);
    console.log(`  statement: ${row.statement}`);
    console.log(`  captured: ${row.provenance?.capturedAt ?? "unknown"} source=${row.provenance?.source ?? "unknown"}`);
    if (row.contradictoryTo) {
      const target = byId.get(row.contradictoryTo);
      console.log(`  contradictoryTo: ${row.contradictoryTo}${target ? ` -> ${target.statement}` : ""}`);
    }
  }
}