import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { IntelligenceProvider, PipelineStage } from "../core/contracts.js";
import { resolveAssetPath, workspaceStorageDir } from "../dream/dreamer-home.js";
import type { DreamContext } from "../core/types.js";
import { createConsolidationTools } from "./consolidation-stage-tools.js";

async function loadPrompt(insights: string[], orientationPath: string): Promise<string> {
  const insightList = insights.length
    ? insights.map((s, i) => `${i + 1}. ${s}`).join("\n")
    : "(none — only review and prune existing memories)";
  try {
    const template = await readFile(resolveAssetPath("prompts/consolidation-stage.md"), "utf8");
    return template.replace("{{insights}}", insightList).replace("{{orientation_path}}", orientationPath);
  } catch {
    return `Consolidate these insights into long-term memory.\n\nNew insights:\n${insightList}\n\nCall list_memories, then write_memory or remove_memory as appropriate.`;
  }
}

export class ConsolidationStage implements PipelineStage {
  readonly id = "stage.consolidation";

  constructor(private readonly provider: IntelligenceProvider) {}

  async run(context: DreamContext): Promise<DreamContext> {
    // Remove autogenerated noise from previous runs
    const priorCount = context.memories.length;
    context.memories = context.memories.filter((m) => !m.statement.startsWith("Observed "));
    const removedNoise = priorCount - context.memories.length;
    if (removedNoise > 0) context.diary.push(`consolidation:removed-noise-memories=${removedNoise}`);

    if (context.insights.length === 0 && context.memories.length === 0) return context;

    const runDir = join(workspaceStorageDir(context.workspaceDir), "runs", context.runId);
    const orientationPath = join(runDir, "orientation.md");
    const { tools, applyChanges } = createConsolidationTools(context.memories, context.nowIso);
    const prompt = await loadPrompt(context.insights, orientationPath);

    try {
      await this.provider.runAgent(prompt, tools, [
        "Finish consolidation. Write any remaining memories and call remove_memory for anything contradicted."
      ]);
    } catch (error) {
      context.diary.push(`consolidation:agent_error=${String(error).slice(0, 120)}`);
    }

    applyChanges(context);
    context.diary.push(`consolidation:memories_added=${context.metrics.memoriesAdded}`);
    return context;
  }
}
