import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { IntelligenceProvider, PipelineStage } from "../core/contracts.js";
import { resolveAssetPath, workspaceStorageDir } from "../dream/dreamer-home.js";
import type { DreamContext, InsightRecord } from "../core/types.js";
import type { RuntimeStageAgentPackConfig } from "../dream/runtime-manifest.js";
import { createConsolidationTools } from "./consolidation-stage-tools.js";
import { loadStageTemplate, renderStageTemplate } from "./stage-agent-templates.js";

function formatInsights(insights: InsightRecord[]): string {
  if (!insights.length) return "(none - only review and prune existing memories)";
  return insights
    .map((insight, index) => {
      const parts = [`${index + 1}. statement: ${insight.statement}`, `   scope: ${insight.scope}`];
      if (insight.context?.category) parts.push(`   category: ${insight.context.category}`);
      if (insight.context?.tags?.length) parts.push(`   tags: ${insight.context.tags.join(", ")}`);
      if (insight.context?.rationale) parts.push(`   rationale: ${insight.context.rationale}`);
      if (insight.context?.appliesWhen) parts.push(`   applies_when: ${insight.context.appliesWhen}`);
      if (insight.capture?.horizon) parts.push(`   horizon: ${insight.capture.horizon}`);
      if (insight.capture?.expiresAt) parts.push(`   expires_at: ${insight.capture.expiresAt}`);
      if (insight.capture?.reason) parts.push(`   reason: ${insight.capture.reason}`);
      if (insight.capture?.references?.length) {
        const references = insight.capture.references.map((ref) => `${ref.kind}:${ref.value}`).join("; ");
        parts.push(`   references: ${references}`);
      }
      if (insight.evidence?.length) {
        const evidence = insight.evidence
          .map((item) => {
            const fields: string[] = [];
            if (item.sessionId) fields.push(`session_id=${item.sessionId}`);
            if (item.fromMessage) fields.push(`from=${item.fromMessage}`);
            if (item.toMessage) fields.push(`to=${item.toMessage}`);
            return fields.length ? fields.join(" ") : "unscoped";
          })
          .join("; ");
        parts.push(`   evidence: ${evidence}`);
      }
      return parts.join("\n");
    })
    .join("\n");
}

async function loadPrompt(insights: InsightRecord[], orientationPath: string): Promise<string> {
  const insightList = insights.length
    ? formatInsights(insights)
    : "(none - only review and prune existing memories)";
  try {
    const template = await readFile(resolveAssetPath("prompts/consolidation-stage.md"), "utf8");
    return template.replace("{{insights}}", insightList).replace("{{orientation_path}}", orientationPath);
  } catch {
    return `Consolidate these insights into long-term memory.\n\nNew insights:\n${insightList}\n\nCall list_memories, then write_memory or remove_memory as appropriate.`;
  }
}

export class ConsolidationStage implements PipelineStage {
  readonly id = "stage.consolidation";

  constructor(
    private readonly provider: IntelligenceProvider,
    private readonly agentPack?: RuntimeStageAgentPackConfig
  ) {}

  async run(context: DreamContext): Promise<DreamContext> {
    // Remove autogenerated noise from previous runs
    const priorCount = context.memories.length;
    context.memories = context.memories.filter((m) => !m.statement.startsWith("Observed "));
    const removedNoise = priorCount - context.memories.length;
    if (removedNoise > 0) context.diary.push(`consolidation:removed-noise-memories=${removedNoise}`);

    if (context.insights.length === 0 && context.memories.length === 0) return context;

    const runDir = join(workspaceStorageDir(context.workspaceDir), "runs", context.runId);
    const orientationPath = join(runDir, "orientation.md");
    const { tools, applyChanges } = createConsolidationTools(
      context.memories,
      context.nowIso,
      context.insights,
      context.runId,
      context.workspaceDir,
      runDir
    );
    const prompt = await loadPrompt(context.insights, orientationPath);
    const customAgents = this.agentPack
      ? await Promise.all(
          this.agentPack.customAgents.map(async (agent) => ({
            name: agent.name,
            displayName: agent.displayName,
            description: agent.description,
            tools: agent.tools,
            infer: agent.infer,
            prompt: renderStageTemplate(
              await loadStageTemplate(
                context.workspaceDir,
                agent.promptTemplatePath,
                "Review all memories and produce consolidation recommendations."
              ),
              { run_dir: runDir, orientation_path: orientationPath }
            )
          }))
        )
      : undefined;
    const explicitSequence =
      this.agentPack?.execution?.mode === "explicit-sequence" ? this.agentPack.execution.explicitSequence ?? [] : [];

    try {
      const runOptions = {
        streamTag: "consolidation agent",
        retries: [
          "Finish consolidation. Write any remaining memories and call remove_memory for anything contradicted."
        ],
        customAgents,
        defaultAgent: this.agentPack?.defaultAgent
      };
      if (customAgents && explicitSequence.length > 0) {
        const customAgentByName = new Map(customAgents.map((agent) => [agent.name, agent]));
        for (const agentName of explicitSequence) {
          const selectedAgent = customAgentByName.get(agentName);
          if (!selectedAgent) continue;
          await this.provider.runAgent(selectedAgent.prompt, tools, { ...runOptions, selectedAgent: agentName, retries: [] });
        }
      } else {
        await this.provider.runAgent(prompt, tools, runOptions);
      }
    } catch (error) {
      context.diary.push(`consolidation:agent_error=${String(error).slice(0, 120)}`);
    }

    applyChanges(context);
    context.diary.push(`consolidation:memories_added=${context.metrics.memoriesAdded}`);
    return context;
  }
}
