import { mkdir, readFile, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { IntelligenceProvider } from "../core/contracts.js";
import { assertSafeWritePath } from "../core/safety.js";
import type { DreamContext } from "../core/types.js";
import type { DreamConfig } from "./config.js";

type GeneratedFile = { path: string; content: string };

type GeneratedResponse = {
  files?: GeneratedFile[];
};

function stripCodeFence(text: string): string {
  const match = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  return match?.[1]?.trim() ?? text.trim();
}

function parseResponse(raw: string): GeneratedFile[] {
  const cleaned = stripCodeFence(raw);
  try {
    const parsed = JSON.parse(cleaned) as GeneratedResponse;
    if (!Array.isArray(parsed.files)) return [];
    return parsed.files.filter(
      (file) => typeof file?.path === "string" && typeof file?.content === "string" && file.path.trim().length > 0
    );
  } catch {
    return [];
  }
}

function renderPrompt(template: string, context: DreamContext, config: DreamConfig): string {
  const events = context.events
    .slice(0, config.docsMaxEvents)
    .map((event) => `- [${event.kind}] ${event.text}`)
    .join("\n");
  const memories = context.memories
    .slice(0, config.docsMaxMemories)
    .map((memory) => `- ${memory.statement}`)
    .join("\n");
  const signalLines = context.signals.slice(0, config.docsMaxSignals).map((signal) => `- ${signal}`).join("\n");
  const hintsPath = assertSafeWritePath(context.workspaceDir, join(context.workspaceDir, config.docsImprovementHintsPath));

  let hints = "- none";
  try {
    // Improvement hints are generated by the self-improvement loop and can be empty.
    const rawHints = readFileSync(hintsPath, "utf8").trim();
    hints = rawHints.length > 0 ? rawHints : "- none";
  } catch {
    hints = "- none";
  }

  return template
    .replaceAll("{{signals}}", signalLines)
    .replaceAll("{{memories}}", memories)
    .replaceAll("{{events}}", events)
    .replaceAll("{{improvementHints}}", hints);
}

export async function writeProviderDocs(
  context: DreamContext,
  provider: IntelligenceProvider,
  config: DreamConfig
): Promise<void> {
  const outDir = assertSafeWritePath(context.workspaceDir, join(context.workspaceDir, config.docsOutputRootPath));
  await mkdir(outDir, { recursive: true });
  const promptTemplatePath = assertSafeWritePath(
    context.workspaceDir,
    join(context.workspaceDir, config.docsPromptTemplatePath)
  );
  const promptTemplate = await readFile(promptTemplatePath, "utf8");
  const prompt = renderPrompt(promptTemplate, context, config);
  const raw = await provider.summarize(prompt);
  context.providerOutputs.documentationPlan = raw;

  const files = parseResponse(raw);
  if (!files.length) {
    const fallbackPath = assertSafeWritePath(context.workspaceDir, join(context.workspaceDir, config.docsFallbackOutputPath));
    await mkdir(dirname(fallbackPath), { recursive: true });
    await writeFile(fallbackPath, `${raw.trim()}\n`, "utf8");
    context.metrics.docsGenerated += 1;
    context.diary.push("documentation:provider_raw_output");
    return;
  }

  const normalizedOutputRoot = config.docsOutputRootPath.replace(/^\/+/, "").replace(/\/+$/, "");
  for (const file of files) {
    const sanitizedPath = file.path.replace(/\\/g, "/").replace(/^\/+/, "");
    const safeRelative = sanitizedPath
      .replace(new RegExp(`^${normalizedOutputRoot}/`), "")
      .replace(/^\/+/, "")
      .replace(/^docs\//, "");
    const filePath = assertSafeWritePath(context.workspaceDir, join(outDir, safeRelative));
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, `${file.content.trim()}\n`, "utf8");
    context.metrics.docsGenerated += 1;
  }
  context.diary.push(`documentation:provider_files=${files.length}`);
}
