import { Command } from "commander";
import { cwd } from "node:process";
import { runDream } from "./dream/run-dream.js";
import { runScheduled } from "./dream/schedule.js";
import { runSetupInit } from "./cli/setup-init.js";
import { runSetupDoctor } from "./cli/setup-doctor.js";
import { runMetricsSummary, runObservabilitySummary } from "./cli/reports.js";
import { runInspectMemories } from "./cli/inspect-memories.js";
import { runInspectInsights } from "./cli/inspect-insights.js";

const program = new Command();
program.name("dreamer").description("Agentic dreaming system");
program.showHelpAfterError();
program.showSuggestionAfterError();

program
  .command("run")
  .description("Run one dream cycle")
  .option("--replay-from-start", "ignore saved cursor and ingest from the start")
  .option("--no-persist-state", "do not write .dreamer/state.json after this run")
  .action(async (options: { replayFromStart?: boolean; persistState?: boolean }) => {
    await runDream(cwd(), {
      replayFromStart: options.replayFromStart,
      persistState: options.persistState
    });
  });

program
  .command("schedule")
  .description("Run scheduled dream cycles")
  .option("--interval-ms <number>", "interval in milliseconds", "86400000")
  .option("--once", "run once and exit", false)
  .action(async (options: { intervalMs: string; once: boolean }) => {
    const interval = Number(options.intervalMs);
    await runScheduled(cwd(), interval, options.once);
  });

const setupCommand = program.command("setup").description("Setup, integration checks, and provider onboarding helpers");

setupCommand
  .command("init")
  .description("Show setup summary and optionally write missing provider env placeholders")
  .option("--write-env", "append missing provider env placeholders to .env.local", false)
  .action(async (options: { writeEnv: boolean }) => {
    await runSetupInit(cwd(), options.writeEnv);
  });

setupCommand
  .command("doctor")
  .description("Run integration/provider diagnostics against current runtime config")
  .option("--strict", "treat warnings as failures", false)
  .action(async (options: { strict: boolean }) => {
    await runSetupDoctor(cwd(), options.strict);
  });

program
  .command("metrics")
  .description("Show numeric run counters from reports/metrics.json")
  .action(async () => {
    await runMetricsSummary(cwd());
  });

program
  .command("status")
  .description("Show report file status and latest run metadata")
  .action(async () => {
    await runObservabilitySummary(cwd());
  });

const inspectCommand = program.command("inspect").description("Inspect memories and generated insights");

inspectCommand
  .command("memories")
  .description("Inspect memory records from local backends")
  .option("--source <source>", "file|copilot|honcho|all", "all")
  .option("--scope <scope>", "user|workspace|session")
  .option("--limit <number>", "maximum rows", "20")
  .option("--prune-noise", "remove autogenerated Observed* noise before listing", false)
  .option("--json", "print raw JSON", false)
  .action(async (options: { source: "file" | "copilot" | "honcho" | "all"; scope?: "user" | "workspace" | "session"; limit: string; pruneNoise: boolean; json: boolean }) => {
    await runInspectMemories(cwd(), {
      source: options.source,
      scope: options.scope,
      limit: Number(options.limit),
      contradictionsOnly: false,
      pruneNoise: options.pruneNoise,
      json: options.json
    });
  });

inspectCommand
  .command("contradictions")
  .description("Inspect only contradictory memory records")
  .option("--source <source>", "file|copilot|honcho|all", "all")
  .option("--limit <number>", "maximum rows", "20")
  .option("--prune-noise", "remove autogenerated Observed* noise before listing", false)
  .option("--json", "print raw JSON", false)
  .action(async (options: { source: "file" | "copilot" | "honcho" | "all"; limit: string; pruneNoise: boolean; json: boolean }) => {
    await runInspectMemories(cwd(), {
      source: options.source,
      limit: Number(options.limit),
      contradictionsOnly: true,
      pruneNoise: options.pruneNoise,
      json: options.json
    });
  });

inspectCommand
  .command("insights")
  .description("Inspect latest evaluation and pipeline insights")
  .option("--json", "print raw JSON", false)
  .action(async (options: { json: boolean }) => {
    await runInspectInsights(cwd(), options.json);
  });

if (process.argv.slice(2).length === 0) {
  program.outputHelp();
  process.exitCode = 1;
} else {
  await program.parseAsync(process.argv);
}
