import { describe, expect, it } from "vitest";
import { ConsolidationStage } from "../../src/stages/consolidation-stage.js";
import { buildContext } from "../../src/dream/build-context.js";

describe("ConsolidationStage", () => {
  it("adds new memory and updates duplicates only for explicit insights", async () => {
    const stage = new ConsolidationStage();
    const context = buildContext(process.cwd(), "run-x");
    context.signals = ["session_starts=1", "insight:Use fast failing tests before refactors", "insight:Use fast failing tests before refactors"];
    const first = await stage.run(context);
    expect(first.memories.length).toBe(1);
    expect(first.memories[0]?.statement).toBe("Use fast failing tests before refactors");
    const second = await stage.run(first);
    expect(second.metrics.memoriesUpdated).toBeGreaterThan(0);
  });

  it("removes autogenerated Observed memory noise", async () => {
    const stage = new ConsolidationStage();
    const context = buildContext(process.cwd(), "run-y");
    context.memories.push({
      id: "mem-noise",
      scope: "workspace",
      statement: "Observed message_events=24",
      confidence: 0.7,
      provenance: { source: "dream-run", eventIds: [], capturedAt: context.nowIso }
    });
    context.memories.push({
      id: "mem-keep",
      scope: "workspace",
      statement: "Use explicit rollback plans for risky migrations",
      confidence: 0.9,
      provenance: { source: "dream-run-intelligence", eventIds: [], capturedAt: context.nowIso }
    });

    const result = await stage.run(context);
    expect(result.memories.map((memory) => memory.statement)).toEqual([
      "Use explicit rollback plans for risky migrations"
    ]);
  });
});
