import { mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { ConsolidationStage } from "../../src/stages/consolidation-stage.js";
import { buildContext } from "../../src/dream/build-context.js";
import { createConsolidationTools } from "../../src/stages/consolidation-stage-tools.js";
import type { IntelligenceProvider, RunAgentOptions } from "../../src/core/contracts.js";
import type { RuntimeStageAgentPackConfig } from "../../src/dream/runtime-manifest.js";

const stubProvider = {
  id: "provider.stub",
  summarize: async () => "",
  runAgent: async () => ""
};

const MAIN_CONSOLIDATION_EXCLUDED_TOOLS = [
  "list_memories",
  "read_reference",
  "bash",
  "read_bash",
  "view",
  "grep_search",
  "file_search",
  "semantic_search",
  "list_dir",
  "run_in_terminal",
  "send_to_terminal",
  "get_terminal_output",
  "terminal_last_command"
];

describe("ConsolidationStage", () => {
  it("writes insights from context.insights via AI agent tools", async () => {
    let writeCount = 0;
    const provider = {
      ...stubProvider,
      runAgent: async (_prompt: string, tools: unknown[]) => {
        const typedTools = tools as Array<{ name: string; handler: (args: Record<string, unknown>) => unknown }>;
        const writeTool = typedTools.find((t) => t.name === "write_memory");
        const listTool = typedTools.find((t) => t.name === "list_memories");
        const finalizeTool = typedTools.find((t) => t.name === "finalize_consolidation");
        listTool?.handler({});
        writeTool?.handler({
          statement: "Use fast failing tests before refactors",
          scope: "workspace",
          confidence: 0.9,
          horizon: "long_term",
          reason: "Repeated user correction showed this is a durable engineering practice.",
          references: [{ kind: "file", value: "docs/prd.md" }]
        });
        writeTool?.handler({
          statement: "Use fast failing tests before refactors",
          scope: "workspace",
          confidence: 0.9,
          horizon: "long_term",
          reason: "Repeated user correction showed this is a durable engineering practice.",
          references: [{ kind: "file", value: "docs/prd.md" }]
        });
        finalizeTool?.handler({
          status: "completed",
          summary: "Recorded durable testing preference and merged duplicates."
        });
        writeCount++;
        return "";
      }
    };
    const stage = new ConsolidationStage(provider);
    const context = buildContext(process.cwd(), "run-x");
    context.insights = [{ statement: "Use fast failing tests before refactors", scope: "workspace" }];
    const result = await stage.run(context);
    expect(writeCount).toBe(1);
    expect(result.memories.length).toBe(1);
    expect(result.memories[0]?.statement).toBe("Use fast failing tests before refactors");
    // Writing same statement again bumps confidence, not adds duplicate
    expect(result.memories[0]?.confidence).toBeGreaterThan(0.9);
  });

  it("removes autogenerated Observed memory noise before running", async () => {
    const stage = new ConsolidationStage(stubProvider);
    const context = buildContext(process.cwd(), "run-y");
    context.memories.push({
      id: "mem-noise",
      scope: "workspace",
      statement: "Observed message_events=24",
      confidence: 0.7,
      provenance: { source: "dream-run", eventIds: [], capturedAt: context.nowIso }
    });
    context.memories.push({
      id: "mem-keep",
      scope: "workspace",
      statement: "Use explicit rollback plans for risky migrations",
      confidence: 0.9,
      provenance: { source: "dream-run-intelligence", eventIds: [], capturedAt: context.nowIso }
    });
    const result = await stage.run(context);
    expect(result.memories.map((m) => m.statement)).toEqual([
      "Use explicit rollback plans for risky migrations"
    ]);
  });

  it("lets consolidation validate cited workspace and session references", async () => {
    const workspaceDir = join(tmpdir(), `dreamer-consolidation-${Date.now()}`);
    const runDir = join(workspaceDir, ".dreamer-run");
    await mkdir(join(runDir, "sessions"), { recursive: true });
    await writeFile(join(workspaceDir, "AGENTS.md"), "Use pnpm for this repo.\n", "utf8");
    await writeFile(join(runDir, "sessions", "session-1.md"), "[1] **user**\nPrefer pnpm.\n", "utf8");

    try {
      const { tools } = createConsolidationTools([], "2026-05-10T00:00:00.000Z", [], "run-test", workspaceDir, runDir);
      const readReference = tools.find((tool) => tool.name === "read_reference") as
        | { handler: (args: Record<string, unknown>) => Promise<{ textResultForLlm: string; resultType: string }> }
        | undefined;

      const fileResult = await readReference?.handler({ kind: "file", value: "AGENTS.md" });
      const sessionResult = await readReference?.handler({ kind: "session", value: "session-1" });
      const runResult = await readReference?.handler({ kind: "doc", value: "dream-run:run-test" });
      const blocked = await readReference?.handler({ kind: "file", value: "/etc/passwd" });

      expect(fileResult?.textResultForLlm).toContain("Use pnpm");
      expect(sessionResult?.textResultForLlm).toContain("Prefer pnpm");
      expect(runResult?.resultType).toBe("success");
      expect(blocked?.resultType).toBe("error");
    } finally {
      await rm(workspaceDir, { recursive: true, force: true });
    }
  });

  it("rejects write_memory references that do not exist", async () => {
    const workspaceDir = join(tmpdir(), `dreamer-consolidation-write-${Date.now()}`);
    const runDir = join(workspaceDir, ".dreamer-run");
    await mkdir(join(runDir, "sessions"), { recursive: true });
    await writeFile(join(workspaceDir, "AGENTS.md"), "Use pnpm for this repo.\n", "utf8");
    await writeFile(join(runDir, "sessions", "session-1.md"), "[1] **user**\nPrefer pnpm.\n", "utf8");

    try {
      const { tools } = createConsolidationTools([], "2026-05-10T00:00:00.000Z", [], "run-test", workspaceDir, runDir);
      const writeMemory = tools.find((tool) => tool.name === "write_memory") as
        | { handler: (args: Record<string, unknown>) => { textResultForLlm: string; resultType: string } }
        | undefined;

      const missingRef = writeMemory?.handler({
        statement: "Use explicit rollback plans for risky migrations",
        scope: "workspace",
        horizon: "long_term",
        reason: "This is a validated durable engineering preference.",
        references: [{ kind: "file", value: "DOES_NOT_EXIST.md" }]
      });
      const existingRef = writeMemory?.handler({
        statement: "Prefer pnpm for this repository",
        scope: "workspace",
        horizon: "long_term",
        reason: "This preference is explicit and stable across sessions.",
        references: [{ kind: "session", value: "1" }]
      });

      expect(missingRef?.resultType).toBe("error");
      expect(missingRef?.textResultForLlm).toContain("Reference target not found");
      expect(existingRef?.resultType).toBe("success");
    } finally {
      await rm(workspaceDir, { recursive: true, force: true });
    }
  });

  it("passes consolidation specialist agents to the provider", async () => {
    const calls: Array<{ prompt: string; options: RunAgentOptions; toolNames: string[] }> = [];
    const provider: IntelligenceProvider = {
      id: "provider.test",
      summarize: async () => "",
      runAgent: async (prompt: string, tools: unknown[], options: RunAgentOptions = {}) => {
        calls.push({
          prompt,
          options,
          toolNames: tools.map((tool) => String((tool as { name?: unknown }).name ?? "unknown"))
        });
        const typedTools = tools as Array<{ name: string; handler: (args: Record<string, unknown>) => unknown }>;
        const finalizeTool = typedTools.find((tool) => tool.name === "finalize_consolidation");
        finalizeTool?.handler({ status: "no_changes_needed", summary: "No durable changes required after review." });
        return "";
      }
    };
    const pack: RuntimeStageAgentPackConfig = {
      defaultAgent: { excludedTools: MAIN_CONSOLIDATION_EXCLUDED_TOOLS },
      customAgents: [
        {
          name: "memory-inventory-reviewer",
          tools: ["bash", "read_bash", "view", "list_memories", "read_reference"],
          promptTemplatePath: "prompts/stages/consolidation/agents/memory-inventory-reviewer.md",
          infer: false
        },
        {
          name: "contradiction-scope-reviewer",
          tools: ["bash", "read_bash", "view", "list_memories", "read_reference"],
          promptTemplatePath: "prompts/stages/consolidation/agents/contradiction-scope-reviewer.md",
          infer: false
        },
        {
          name: "reference-validator",
          tools: ["bash", "read_bash", "view", "list_memories", "read_reference"],
          promptTemplatePath: "prompts/stages/consolidation/agents/reference-validator.md",
          infer: false
        }
      ]
    };
    const stage = new ConsolidationStage(provider, pack);
    const context = buildContext(process.cwd(), "run-agents");
    context.memories.push({
      id: "mem-1",
      scope: "user",
      statement: "Always commit and push after every change",
      confidence: 0.8,
      provenance: { source: "test", eventIds: [], capturedAt: context.nowIso }
    });

    await stage.run(context);

    expect(calls).toHaveLength(1);
    expect(calls[0]?.options.selectedAgent).toBeUndefined();
    expect(calls[0]?.options.defaultAgent).toEqual({ excludedTools: MAIN_CONSOLIDATION_EXCLUDED_TOOLS });
    expect(calls[0]?.options.customAgents?.map((agent) => agent.name)).toEqual([
      "memory-inventory-reviewer",
      "contradiction-scope-reviewer",
      "reference-validator"
    ]);
    expect(calls[0]?.toolNames).toEqual([
      "list_memories",
      "read_reference",
      "write_memory",
      "remove_memory",
      "finalize_consolidation"
    ]);
    expect(calls[0]?.options.customAgents?.[0]?.prompt).toContain("memory inventory reviewer");
    expect(calls[0]?.options.customAgents?.[1]?.prompt).toContain("conditional_compatibility");
    expect(calls[0]?.options.customAgents?.[2]?.prompt).toContain("Do not call write_memory");
    expect(calls[0]?.prompt).toContain("Have specialist agents review the full memory store");
    expect(calls[0]?.prompt).toContain("The main consolidation agent should not call file, shell, list, or reference-inspection tools directly");
  });

  it("insists on finalize_consolidation and skips applying changes when verdict is missing", async () => {
    const prompts: string[] = [];
    const provider: IntelligenceProvider = {
      id: "provider.test",
      summarize: async () => "",
      runAgent: async (prompt: string) => {
        prompts.push(prompt);
        return "";
      }
    };

    const stage = new ConsolidationStage(provider);
    const context = buildContext(process.cwd(), "run-no-verdict");
    context.insights = [{ statement: "Use concise status updates", scope: "workspace" }];
    const result = await stage.run(context);

    expect(prompts.length).toBe(2);
    expect(result.diary).toContain("consolidation:missing_final_verdict=1");
    expect(result.diary).toContain("consolidation:user_message=Consolidation must call finalize_consolidation to finish.");
    expect(result.diary.some((line) => line.startsWith("consolidation:memories_added="))).toBe(false);
  });
});
