import { describe, expect, it } from "vitest";
import { ConsolidationStage } from "../../src/stages/consolidation-stage.js";
import { buildContext } from "../../src/dream/build-context.js";

const stubProvider = {
  id: "provider.stub",
  summarize: async () => "",
  runAgent: async () => ""
};

describe("ConsolidationStage", () => {
  it("writes insights from context.insights via AI agent tools", async () => {
    let writeCount = 0;
    const provider = {
      ...stubProvider,
      runAgent: async (_prompt: string, tools: unknown[]) => {
        const typedTools = tools as Array<{ name: string; handler: (args: Record<string, unknown>) => unknown }>;
        const writeTool = typedTools.find((t) => t.name === "write_memory");
        const listTool = typedTools.find((t) => t.name === "list_memories");
        listTool?.handler({});
        writeTool?.handler({
          statement: "Use fast failing tests before refactors",
          scope: "workspace",
          confidence: 0.9,
          horizon: "long_term",
          reason: "Repeated user correction showed this is a durable engineering practice.",
          references: [{ kind: "session", value: "session-1" }]
        });
        writeTool?.handler({
          statement: "Use fast failing tests before refactors",
          scope: "workspace",
          confidence: 0.9,
          horizon: "long_term",
          reason: "Repeated user correction showed this is a durable engineering practice.",
          references: [{ kind: "session", value: "session-1" }]
        });
        writeCount++;
        return "";
      }
    };
    const stage = new ConsolidationStage(provider);
    const context = buildContext(process.cwd(), "run-x");
    context.insights = [{ statement: "Use fast failing tests before refactors", scope: "workspace" }];
    const result = await stage.run(context);
    expect(writeCount).toBe(1);
    expect(result.memories.length).toBe(1);
    expect(result.memories[0]?.statement).toBe("Use fast failing tests before refactors");
    // Writing same statement again bumps confidence, not adds duplicate
    expect(result.memories[0]?.confidence).toBeGreaterThan(0.9);
  });

  it("removes autogenerated Observed memory noise before running", async () => {
    const stage = new ConsolidationStage(stubProvider);
    const context = buildContext(process.cwd(), "run-y");
    context.memories.push({
      id: "mem-noise",
      scope: "workspace",
      statement: "Observed message_events=24",
      confidence: 0.7,
      provenance: { source: "dream-run", eventIds: [], capturedAt: context.nowIso }
    });
    context.memories.push({
      id: "mem-keep",
      scope: "workspace",
      statement: "Use explicit rollback plans for risky migrations",
      confidence: 0.9,
      provenance: { source: "dream-run-intelligence", eventIds: [], capturedAt: context.nowIso }
    });
    const result = await stage.run(context);
    expect(result.memories.map((m) => m.statement)).toEqual([
      "Use explicit rollback plans for risky migrations"
    ]);
  });
});

