import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { runInspectMemories } from "../../src/cli/inspect-memories.js";
import { workspaceStorageDir } from "../../src/dream/dreamer-home.js";

const tempDirs: string[] = [];

afterEach(() => {
  for (const dir of tempDirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

describe("runInspectMemories", () => {
  it("prunes autogenerated Observed noise when requested", async () => {
    const workspaceDir = mkdtempSync(join(tmpdir(), "dreamer-inspect-"));
    tempDirs.push(workspaceDir);
    const storageDir = workspaceStorageDir(workspaceDir);
    mkdirSync(storageDir, { recursive: true });

    writeFileSync(
      join(storageDir, "memory.json"),
      JSON.stringify([
        {
          id: "noise-1",
          scope: "workspace",
          statement: "Observed message_events=24",
          confidence: 0.7,
          provenance: { source: "dream-run", eventIds: [], capturedAt: "2026-05-09T00:00:00.000Z" }
        },
        {
          id: "keep-1",
          scope: "workspace",
          statement: "Use explicit validation before merge",
          confidence: 0.9,
          provenance: { source: "dream-run-intelligence", eventIds: [], capturedAt: "2026-05-09T00:00:00.000Z" }
        }
      ]),
      "utf8"
    );

    const output = vi.spyOn(console, "log").mockImplementation(() => undefined);
    try {
      await runInspectMemories(workspaceDir, {
        source: "file",
        limit: 20,
        contradictionsOnly: false,
        pruneNoise: true,
        json: false
      });
    } finally {
      output.mockRestore();
    }

    const after = JSON.parse(readFileSync(join(storageDir, "memory.json"), "utf8")) as Array<{
      statement: string;
    }>;
    expect(after).toHaveLength(1);
    expect(after[0]?.statement).toBe("Use explicit validation before merge");
  });
});
